# Generated by Django 5.1.4 on 2024-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
