# Generated by Django 5.1.4 on 2024-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_carouselmodel_blogpostmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='heading2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='heading2Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='heading3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='heading3Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='important',
            field=models.TextField(blank=True, null=True),
        ),
    ]
