# Generated by Django 5.1.4 on 2024-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostmodel_heading2_blogpostmodel_heading2content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='important',
            field=models.TextField(blank=True, default='Thanks for visit Mera News', null=True),
        ),
    ]
