# Generated by Django 5.1.4 on 2024-12-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpostmodel_important'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselModel',
        ),
    ]
