# Generated by Django 5.1.4 on 2024-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_carouselmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('health', 'Health'), ('education', 'Education'), ('travel', 'Travel')], default='tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
