# Generated by Django 5.1.4 on 2025-01-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpostmodel_likes_alter_blogpostmodel_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='likes',
        ),
    ]
